[package]
name = "rust"
version = "1.2.3"
authors = ["jsktlang"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "rust"
path = "main.rs"
